# Site settings
title: "Ken Jones"
description: "Full Stack Data Scientist"
baseurl: "/whoami" 
url: "https://nightcrawlerai.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Social Links
author:
  name: "Ken Jones"
  avatar: "/assets/images/profile.jpg" 
  bio: "Innovative and versatile developer and researcher."
  location: "Oakland, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/NightCrawlerAI"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/kenrjones1"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kenrjones@berkeley.edu"

# Navigation Links
collections:
  pages:
    output: true
    permalink: /:path/

# Plugins/Extensions
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate

# Exclusions (ignore these files/directories during build)
exclude:
  - "README.md"
  - "KJ Bio.Rmd"