# Site settings
title: "Ken Jones - Resume"
description: "Full Stack Data Scientist"
baseurl: "" # Left empty because deploying to GitHub Pages
url: "https://nightcrawlerai.github.io/whoami"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Social Links
author:
  name: "Ken Jones"
  avatar: "/assets/images/profile.jpg" 
  bio: "Innovative and versatile developer and researcher."
  location: "Oakland, CA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/NightCrawlerAI"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/kenrjones1"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kenrjones@berkeley.edu"

# Navigation Links
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"

collections:
  pages:
    output: true
    permalink: /:path/

# Plugins/Extensions
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclusions (ignore these files/directories during build)
exclude:
  - "README.md"
  - "KJ Bio.Rmd"